### ISSUE TITLE
how to use

### ISSUE THREAD

**Issue by defcdgg** [Kein/SHProto#1]
hi, i tried to build it and got some errors : two same header 'inputstate.h'..
looks like they are using a custom unreal engine.
so how to use this sdk ?

**Comment by Kein** [comment]
Fixed in [#1f9db7be57971ace74d5123db691f78680fd0669](https://github.com/Kein/SHProto/commit/1f9db7be57971ace74d5123db691f78680fd0669)

Engine changes are not part of this repo
